baseURL = 'https://garrett.beatty.codes/'
languageCode = 'en-us'
title = 'Garrett Beatty'
theme = 'nyc-subway'

[params]
  description = "Welcome to Garrett Beatty's portfolio - Navigate through my projects, apps, and publications via the NYC subway-inspired interface"
  author = "Garrett Beatty"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Apps"
    url = "/apps/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4

[imaging]
    quality = 75