baseurl                  = "https://garrett.beatty.codes"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Garrett Beatty"
theme                    = "sam"    # pull in theme as hugo module 
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true

[params]
    homepage             = "Home"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Garrett Beatty"

[[params.videoBackground.sources]]
    source  = "/nyc.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "GarrettBeattyResume.pdf"
    text = "Resume"

[[params.mainMenu]]
    link = "publications"
    text = "Publications"

[[params.mainMenu]]
    link = "projects"
    text = "Projects"

[[params.mainMenu]]
    link = "apps/reader-for-arxiv/privacy"
    text = "Privacy Policy"

[imaging]
    quality = 75